### ISSUE TITLE
encoding to string and decoding to bytearray optimizations

### ISSUE THREAD

**Issue by SmartAudioTools** [mayeut/pybase64#204]
Hi, I'm developing [serializejson](https://github.com/SmartAudioTools/serializejson),  a python library for fast serialization and deserialization of python objects in JSON designed as a safe, interoperable and human-readable drop-in replacement for the Python [pickle](https://docs.python.org/3/library/pickle.html) package.

I use PyBase64 for bytes and bytesarray encoding in json. When encoding and decoding bytes and bytesarrays, most of the time is spend in avoidable copies rather really encoding and decoding in base64.

example with line profiler : 

    import pybase64
    import json
    
    @profile
    def encode_bytearray(bytearray_):
        bytes_b64 = pybase64.b64encode(bytearray_) # 1.05 msec, 29% of time
        string_b64 = bytes_b64.decode("ascii")     # 1.44 msec, 40% of time  
        string_json = f'"{string_b64}"'            # 1.10 msec, 30% of time
        return string_json
    
    @profile
    def decode_bytearray(string_json_without_quotes):
        bytes_b64 = string_json_without_quotes.encode("ascii")  # 1.13 msec, 28% of time 
        bytes_decoded = pybase64.b64decode(bytes_b64)           # 2.00 msec, 52% of time 
        #bytes_decoded = pybase64.b64decode(string_b64)         # 3.72 msec   
        bytearray_decoded  = bytearray(bytes_decoded)           # 0.86 msec, 20% of time
        return bytearray_decoded
    
    # encoding :
    bytearray_ = bytearray(range(256)) * 12000
    string_json = encode_bytearray(bytearray_)

    # decoding : 
    string_json_without_quotes = json.loads(string_json)
    print(string_json_without_quotes.isascii())
    bytearray_decoded = decode_bytearray(string_json)

When encoding, 70% of time is lost in avoidable copies. I would like to know if it could be possible to add an option to encode directly in string to avoid a first copy with bytes_b64.decode("ascii"), and if it could be possible to add an option to encode directly in string with double quotes, to avoid a second copy just for adding double quotes for Json. 

When loading, 48 % of time is lost in avoidable copies.
First, strangely, decoding directly from string is slower than passing by intermediary encoding in bytes even if the string is already ASCII (string_json_without_quotes.isascii() is True)  and so continuous ascii in memory.
Secondly, I would know if it could be possible to add an option to b64decode (or a new function) for decoding directly in bytesarray, in order to avoid a second copy passing by an intermediary bytes.
Sadly, I don't know C and C++ and I'm not comfortable to fork your project or propose a pull request for this améliorations.

Tanks a lot . 

Baptiste

**Comment by mayeut** [comment]
Hi @SmartAudioTools,

Thanks for your feedback on `pybase64`.

Regarding the encoding part, I'm OK with optionnaly returning a `str` object  rather than a `bytes` object which I think would be a common enough usage however, I'm not comfortable adding those double quotes or any kind of prefix/suffix strings at the moment.

Regarding the decoding part:
> First, strangely, decoding directly from string is slower than passing by intermediary encoding in bytes even if the string is already ASCII (string_json_without_quotes.isascii() is True) and so continuous ascii in memory.

I'm only seeing noise in measurements here and the way it works internally is the one you're using (by using `PyUnicode_AsASCIIString` API).
That being said, for `UTF-8` strings, when `validate` is `True` and `altchars` is None, a speed-up can be achieved by working directly on the string buffer.

Returning a `bytesarray` object doesn't seem like a common enough usage but I might add it anyway.

**Comment by SmartAudioTools** [comment]
Hi @mayeut 
Thanks for your response ! 

Regarding the encoding part : 
Good if you could optionnaly returning a str object rather than a bytes object. For the double quotes, I anderstand that you thing it's not a common usage, unfortunately I will waste 50% of the time just to add these quotes. It is a problem of difficulty to add these option or not to overload the API ? 

Regarding the decoding part:
I have updated my example in order to use  validate = True , and making a mean over 100 iterations to avoid noise measurements .
decoding from string is still slower than passing by string decoding in ascii bytes   2.88  msec > 1.16 msec + 1.09 msec
And I guess it could be possble to reduce decoding from string to something about 1.16 msec,  not passing by internal ascii decoding in bytes and  decoding directly from string, beause if string.isascii() is True, internaly string are already stocked in continuous bytes with one byte by char, like bytes.
Returning a bytesarray could by very usefull for all who want to recreate numpy arrays (which are widely used) without data copies, because numpy.array need to be initalizd from bytearray instead of bytes in order to be writeable.


    import pybase64
    import json
    
    @profile
    def encode_bytearray(bytearray_):
        bytes_b64 = pybase64.b64encode(bytearray_) # 1.05 msec, 29% of time
        string_b64 = bytes_b64.decode("ascii")     # 1.44 msec, 40% of time  
        string_json = f'"{string_b64}"'            # 1.10 msec, 30% of time
        return string_json
    
    @profile
    def decode_bytearray(string_json_without_quotes):
        bytes_b64 = string_json_without_quotes.encode("ascii")        # 1.16 msec, 35% of time 
        bytes_decoded = pybase64.b64decode(bytes_b64,validate=True)   # 1.09 msec, 33% of time 
        #bytes_decoded = pybase64.b64decode(string_json_without_quotes, validate=True) # 2.84 msec   
        bytearray_decoded  = bytearray(bytes_decoded)           # 1.01 msec, 31% of time
        return bytearray_decoded
    
    for i in range(100):
        # encoding :
        bytearray_ = bytearray(range(256)) * 12000
        string_json = encode_bytearray(bytearray_)
        
        # decoding :
        string_json_without_quotes = json.loads(string_json)
        print(string_json_without_quotes.isascii())
        bytearray_decoded = decode_bytearray(string_json_without_quotes)

Sinon tu peux me repondre en français si tu n'as pas envie de t'embêter à traduir je suis Lillois ;)

**Comment by mayeut** [comment]
Let's stick to english if someone else comes across this issue.

I'm not getting the same numbers with 100 iterations, it might be related to differences in our python versions, OS, compilers, ...
```
Total time: 0.110393 s
File: profile.py
Function: decode_bytearray_impl at line 13

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    13                                           @profile
    14                                           def decode_bytearray_impl(string_json_without_quotes):
    15       100      40272.0    402.7     36.4      bytes_b64 = string_json_without_quotes.encode("ascii")
    16       100      41478.0    414.8     37.7      bytes_decoded = pybase64.b64decode(bytes_b64, validate=True)
    17                                               #bytes_decoded = pybase64.b64decode(string_json_without_quotes, validate=True)
    18       100      28643.0    286.4     25.9      bytearray_decoded  = bytearray(bytes_decoded)

Total time: 0.106664 s
File: profile.py
Function: decode_bytearray_impl at line 13

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    13                                           @profile
    14                                           def decode_bytearray_impl(string_json_without_quotes):
    15                                               #bytes_b64 = string_json_without_quotes.encode("ascii")
    16                                               #bytes_decoded = pybase64.b64decode(bytes_b64, validate=True)
    17       100      81379.0    813.8     76.3      bytes_decoded = pybase64.b64decode(string_json_without_quotes, validate=True)
    18       100      25285.0    252.8     23.7      bytearray_decoded  = bytearray(bytes_decoded)
```

> And I guess it could be possble to reduce decoding from string to something about 1.16 msec, not passing by internal ascii decoding in bytes and decoding directly from string, beause if string.isascii() is True, internaly string are already stocked in continuous bytes with one byte by char, like bytes.

Yes, it is possible to reduce this in specific cases. Implemented in branch encode_as_string-decode_utf8 if you want to give it a try.

**Comment by SmartAudioTools** [comment]
Thanks ! 
My cumputer is a little old, that explain the differents timing , but you have the same percents . 
Your two optimisations work well, times have been halved! 
I still pass 50 % of the time in avoidable copies adding quotes when encoding and 43 % of time converting to bytearray when decoding, a quote option for encoding_as_string and a decode_as_bytearray would be great !

**Comment by mayeut** [comment]
@SmartAudioTools,

The branch was named with utf-8 because it was created before looking more into how unicode strings are managed in python 3 and I wrongly assumed that I would have to deal with UTF-8 strings (that's also why I was saying `validate` is `True` and `altchars` is `None` would be required which is not the case for Latin-1).

**Comment by mayeut** [comment]
Everything has been added to 1.1.1 release except adding quotes around the string returned by encoding_as_string
