### ISSUE TITLE
Does this library release the GIL?

### ISSUE THREAD

**Issue by apockill** [mayeut/pybase64#293]
Hi! I was wondering if this library releases the Global Interpreter Lock while calling the underlying C bindings? 

Thank you for your library.

**Comment by mayeut** [comment]
Hi @apockill,

The GIL is not released for now.
This is something I've been meaning to do but still need to check the impact for small buffers if any, at least to know (releasing the GIL has probably much more advantages than a potential negative impact for small buffers).

**Comment by apockill** [comment]
Thank you for the response. Would you like any support? Perhaps I can put together a simple benchmark script so that when releasing the gil we can validate what kind of parallelism can be achieved.

**Comment by mayeut** [comment]
> Would you like any support?

That would be great. I will use the existing benchmark to check some things but if you have some ideas to extend this benchmark, by all means, fill free to open a PR.
I'll check today what I can do about the GIL.

**Comment by mayeut** [comment]
PR opened for the feature, still need to run some benchmarks.

**Comment by apockill** [comment]
That's fantastic! I've been trying to figure out ways to unit test these sorts of things. There are tools like [gil load](https://github.com/chrisjbillington/gil_load), and if the gil-locking function takes a long time, it can be detected by having a timer thread (for example, [this test](https://github.com/openvinotoolkit/openvino/pull/6236/files/9b283d1d6f308c06f8bc4431208365b0ad71d5d4#diff-49acff4b1200e749b9045bbf18ade51a94d7609cc4993ffc0c0ba90238f46799R262). 

But it's hard to wrap that into a non-flaky unit test...

**Comment by mayeut** [comment]
> But it's hard to wrap that into a non-flaky unit test...

Right.
I did a few manual tests, while slower in mono-thread on small buffers than the version without GIL support, it's still faster than the stdlib base64 & will allow multithreading.
If there are reports of important regressions, I might add an option to release the GIL instead of releasing it unconditionally.

**Comment by apockill** [comment]
Fantastic, thank you!
