### ISSUE TITLE
msys2 clang64 fails to build

### ISSUE THREAD

**Issue by mayeut** [mayeut/pybase64#718]
Without changes to the code base, msys2 clang64 tests started to fail.
The root cause is still unclear.

Tests disabled in 2bf6adc8d53e0ec6ac10f334b1b2773b176cde92

**Comment by mayeut** [comment]
@MehdiChinoune,

since you helped with #675, maybe you can have look ?

I just know that the cmake build does finish successfully so something else is failing after that but without access to a system to debug that, I'm afraid I can't do much.

Please tell me if you're ok or not with me tagging you in future issues related to msys2.

**Comment by MehdiChinoune** [comment]
I think this something related to the latest msys2-runtime 3.5.3, Consider filing an issue to msys2/MINGW-packages repo.

I don't like when people tagging me.

**Comment by mayeut** [comment]
fixed in a89cb3f1e8b3ab3b8c9dfd0ae2bf2a02525baf16

I guess there was a `gcc` alias that's been removed.
