### ISSUE TITLE
can we get a performant "encodestring" and "decodestring" function?

### ISSUE THREAD

**Issue by thestick613** [mayeut/pybase64#9]
A newline needs to be inserted after every 76 characters.

https://docs.python.org/2/library/base64.html#base64.encodestring
https://docs.python.org/2/library/base64.html#base64.decodestring

**Comment by mayeut** [comment]
Thanks for the suggestion.

These functions are deprecated in Python 3 and have been replaced by the following ones:
https://docs.python.org/3/library/base64.html#base64.encodebytes
https://docs.python.org/3/library/base64.html#base64.decodebytes

`base64.decodebytes` is in fact just a call to `base64.b64decode` so speed-up for this one will be addressed in #4 .

As for encoding, I might be able to look into it.

Just for my information, what use-case(s) are you addressing with these functions ?

**Comment by thestick613** [comment]
I'm still using Python 2 on some legacy code that is being used on rendering emails. The profiler tells me that i'm wasting a lot of time encoding base64 strings.

**Comment by mayeut** [comment]
Running Python 3.6.0
```
python -m pybase64 benchmark ../random 
pybase64 0.2.1 (C extension active - AVX2)
pybase64._pybase64.encodebytes:   1445.619 MB/s (13,271,472 bytes -> 17,928,129 bytes)
base64.encodebytes:                 75.355 MB/s (13,271,472 bytes -> 17,928,129 bytes)
```

@thestick613, I don't know when I'll deploy a new release to PyPI. If you are able to test that it does indeed helps your use case before that, I'd be glad to get your feedback. Thanks

**Comment by thestick613** [comment]
At a first glance, it seems to work faster.

**Comment by mayeut** [comment]
It's now available through  a pip install
